name: build-api

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build API
        run: make build-web
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: bin/
      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.ALWAYS_DATA_HOST }}
          username: ${{ secrets.ALWAYS_DATA_USER }}
          password: ${{ secrets.ALWAYS_DATA_PASSWORD }}
          source: "bin/generate-art"
          target: "/home/git-art-api"